version: '3'

services:
  snap:
    image: snapcore/snapcraft
    volumes:
      - build:/build
      - .:/stage
    working_dir: /stage
    depends_on:
      - piper
    command:
      - "./build.sh"
  piper:
    build: 
      context: ../..
      args:
        - VER=devel
    volumes:
      - build:/build
    command:
      - "/bin/sh"
      - "-c"
      - "/bin/cp /sshpiperd /build/sshpiperd && /build/sshpiperd version && sleep 1h"
volumes:
  build: 
