version: '3.4'

services:
  host-password:
    image: lscr.io/linuxserver/openssh-server:latest
    environment:
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=pass
      - USER_NAME=user
    volumes:
      - shared:/shared
      - sshconfig_password:/config

  host-publickey:
    image: lscr.io/linuxserver/openssh-server:latest
    environment:
      - USER_NAME=user
    volumes:
      - shared:/shared      
      - sshconfig_publickey:/config

  testrunner:
    environment:
      - SSHPIPERD_LOG_LEVEL=trace
      - SSHPIPERD_E2E_TEST=1
    build: 
      context: ../
      target: builder
    volumes:
      - ..:/src
      - shared:/shared
      - sshconfig_publickey:/sshconfig_publickey
      - sshconfig_password:/sshconfig_password
    command: ["./e2eentry.sh"]
    working_dir: /src/e2e
    depends_on:
      - host-publickey
      - host-password

volumes:
  shared:
    driver_opts:
      type: tmpfs
      device: tmpfs

  sshconfig_publickey:

  sshconfig_password: