version: '3.4'

services:
  host-password:
    image: lscr.io/linuxserver/openssh-server:latest
    environment:
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=pass
      - USER_NAME=user
    labels:
      - sshpiper.username=pass
      - sshpiper.container_username=user
      - sshpiper.port=2222
    volumes:
      - shared:/shared
      - sshconfig_password:/config

  host-publickey:
    image: lscr.io/linuxserver/openssh-server:latest
    environment:
      - USER_NAME=user
    volumes:
      - shared:/shared      
      - sshconfig_publickey:/config

  testrunner:
    environment:
      - SSHPIPERD_LOG_LEVEL=trace
      - SSHPIPERD_E2E_TEST=1
      - SSHPIPERD_DEBUG=${SSHPIPERD_DEBUG}
    build: 
      context: ../
      target: builder
    volumes:
      - ..:/src
      - shared:/shared
      - sshconfig_publickey:/sshconfig_publickey
      - sshconfig_password:/sshconfig_password
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["./e2eentry.sh"]
    privileged: true
    working_dir: /src/e2e
    depends_on:
      - host-publickey
      - host-password

  # ensure sshpiperd image works
  piper-imageonly:
    environment:
      - SSHPIPERD_LOG_LEVEL=trace
    build: ../      

volumes:
  shared:
    driver_opts:
      type: tmpfs
      device: tmpfs

  sshconfig_publickey:

  sshconfig_password: