version: '3'

services:
  host-password:
    image: lscr.io/linuxserver/openssh-server:latest
    environment:
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=pass
      - USER_NAME=user
    volumes:
      - shared:/shared
      - sshconfig_password:/config

  host-publickey:
    image: lscr.io/linuxserver/openssh-server:latest
    environment:
      - USER_NAME=user
    volumes:
      - shared:/shared      
      - sshconfig_publickey:/config

  piper-fixed:
    environment:
      - SSHPIPERD_LOG_LEVEL=trace
    build: ../
    command:
      - "/sshpiperd/sshpiperd"
      - "/sshpiperd/plugins/fixed"
      - "--target"
      - "host-password:2222"
    depends_on:
      - host-password

  piper-workingdir:
    environment:
      - SSHPIPERD_LOG_LEVEL=trace
      - SSHPIPERD_WORKINGDIR_STRICTHOSTKEY=true
    volumes:
      - shared:/shared      
    build: ../
    command:
      - "/sshpiperd/sshpiperd"
      - "/sshpiperd/plugins/workingdir"
      - "--root"
      - "/shared/workingdir"
    depends_on:
      - host-password
      - host-publickey

  testrunner:
    environment:
      - SSHPIPERD_E2E_TEST=1
    build: 
      context: ../
      dockerfile: e2e/Dockerfile_e2e
    volumes:
      - ..:/src
      - shared:/shared
      - sshconfig_publickey:/sshconfig_publickey
      - sshconfig_password:/sshconfig_password
    command: ["bash", "-c", "if [ \"${SSHPIPERD_DEBUG}\" == \"1\" ]; then sleep infinity; else go test -v; fi"]
    working_dir: /src/e2e
    depends_on:
      - piper-fixed
      - piper-workingdir

volumes:
  shared:
    driver_opts:
      type: tmpfs
      device: tmpfs

  sshconfig_publickey:

  sshconfig_password: