name: E2E

on:
  workflow_run:
    workflows: ["Go"]
    types: [completed]
    
jobs:

  E2E:
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: E2E
      run: docker-compose up --build --abort-on-container-exit
      working-directory: sshpiperd/e2e

